# Generated by Django 2.2.3 on 2019-07-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190707_0020'),
        ('products', '0008_auto_20170901_2300'),
    ]

    operations = [
    ]
