# Generated by Django 2.2.3 on 2019-07-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_timestamp'),
        ('products', '0012_product_timestamp'),
    ]

    operations = [
    ]
